### ISSUE TITLE
Unable to Share Specific Chrome Window in Screen Sharing - Shares Entire Screen Instead

### ISSUE THREAD

**Issue by rmasad** [regolith-linux/sway-regolith#16]
**Sway Version:** 1.8

**Description:**
I have encountered a significant issue while attempting to share a specific window from Chrome during video calls or screen sharing sessions (like Google Meets). Instead of sharing just the selected Chrome window, the entire screen gets shared, including all open applications and desktop activities. This problem specifically occurs when trying to share a window; however, sharing a single tab within Chrome or the entire screen functions as expected. This issue raises privacy concerns and limits the flexibility needed during presentations or collaborative work sessions.

**Steps to Reproduce:**

1. Open Chrome and navigate to any website.
2. Start a video call using Google Meets (or any other application where the issue occurs).
3. During the call, choose to share your screen and select the option to share a window.
4. Select a Chrome window from the list of available windows to share.

**Expected Behavior:**
Only the selected Chrome window should be shared with participants, hiding any other applications or desktop activities.

**Actual Behavior:**
The entire screen is shared instead of just the selected Chrome window, displaying all open applications and desktop activities to the participants.

**Comment by SoumyaRanjanPatnaik** [comment]
Hi @rmasad. AFAIK, this is a known issue for sway. Wayland currently lacks a protocol that allows for sharing windows. [This](https://github.com/emersion/xdg-desktop-portal-wlr/issues/107#issuecomment-1860051956) comment tracks the status / progress for window sharing.

**Comment by SoumyaRanjanPatnaik** [comment]
Currently the best workaround for this is to create a headless display and share that instead of one of your physical monitors. You can then move any windows you want to share.

**Comment by SoumyaRanjanPatnaik** [comment]
As a side note, sway 1.9 is availabe in `noble` as part of `regolith 3.2 beta 1` release.  Although it is unlikely to fix this, you can still give it a try. https://regolith-desktop.com/docs/reference/Releases/regolith-3.2-release-notes/

**Comment by rmasad** [comment]
I update to 3.2 beta 1 but now it give me some errors updating:
 regolith-inputd : depends: libglib2.0-0t64 (> = 2.28.0) but it is not installable
 regolith-unclutter-xfixes: depends: libev4t64 (> = 1: 4.04) but it is not installable

**Comment by rmasad** [comment]
Reading the threads on the topic, have you analyzed Regolith+hyprland? It looks like a version of sway with fewer problems.

**Comment by SoumyaRanjanPatnaik** [comment]
The regolith ecosystem was originally built mainly around `i3` as the window manager. `sway`, being as close to a drop-in as possible, made creating a functionally equivalent desktop environment reasonably straightforward. Another benefit of sticking with sway is the stability / backwards compatibility it provides. It has been in development since almost 9-10 years now. In comparison, the development effort required to keep up with Hyprland would probably be significantly more, given its rapid development speed.

That said, imagining a `Hyprland` based version of Regolith is not entirely impossible. I have occasionally considered trying this out as a hobby project, but it would require a lot more time and effort than any of us can spare.

**Comment by rmasad** [comment]
Thanks @SoumyaRanjanPatnaik
